version: "3.9"
services:
  scrapy:
    image: registry.gitlab.com/zacharywilson/scrapy-opensearch/scrapy-opensearch:latest
    build: .
    command: crawl -s OPENSEARCH_ENABLED=True dummy_spider
    volumes:
      - .:/usr/src/app
    environment:
      SCRAPY_OPENSEARCH_HOSTS: https://opensearch:9200
      SCRAPY_LOG_LEVEL: "DEBUG"
    depends_on:
      - opensearch
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - "cluster.name=docker-cluster"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    restart: always
