version: "3.9"

services:
  scrapy:
    image: registry.gitlab.com/zacharywilson/scrapy-opensearch/scrapy-opensearch:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:[cached]
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SCRAPY_OPENSEARCH_ENABLED: true
      SCRAPY_OPENSEARCH_HOSTS: https://opensearch:9200
      SCRAPY_LOG_LEVEL: "DEBUG"
    depends_on:
      - opensearch
    restart: always
    init: true
    command: sleep infinity

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - "cluster.name=docker-cluster"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    restart: always
