OPENSEARCH_ENABLED = False
OPENSEARCH_HOSTS = [{"host": "localhost", "port": 9200}]
OPENSEARCH_USERNAME = OPENSEARCH_PASSWORD = "admin"
OPENSEARCH_INDEX = "scrapy"
OPENSEARCH_USE_SSL = True
OPENSEARCH_VERIFY_CERTS = False
OPENSEARCH_SSL_SHOW_WARN = False
OPENSEARCH_HTTP_COMPRESS = True  # enables gzip compression for request bodies
OPENSEARCH_CA_CERTS = None
OPENSEARCH_CLIENT_CERT = None
OPENSEARCH_CLIENT_KEY = None
